### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Dolaxom** [Dolaxom/C_3DEngine#1]
# 08.11.2022 - 09.11.2022 tasks
## Qt interface
- [x] Set Rotation
- [x] Set Scale
- [x] Set Location (all 3 axles)
- [x] Button Make Screenshoot
- [x] Button Make Gif
- [x] Move rotation CheckBox to Set Rotation
- [x] Add button for perspective and orthogonal projection
- [x] Add widget for choosing the background color
- [x] Add widget for type (solid, dashed), color and thickness of the **edges**
- [x] Add widget for display method (none, circle, square), color and size of the **vertices**
- [x] Add information field about count of polygons and etc.
- [x] Implement errorflags and check for incorrect meshes in Qt
- [x] Add meshpath field, find a path to materials/raw and set placeholder text to point to it, load mesh from the specified folder, check the folder's existence
- [x] Find a convenient way to transport variables from mainwindow to openglwindget (getters, setters?)
- [x] Update changing focus and enterkey events
- [x] Fill info labels
- [x] Find a convenient way to translate color strings to rgb float values
- [x] Assign the values to related functions
- [x] Fix the crash related to dropdown menus
- [x] Save all setttings between program restarts
- [x] Implement auto update on any value change
- [x] Implement auto rotation
- [x] Implement mouse events for openglwidget
- [x] Implement style changing for vertices and edges, color changing for vertices
- [x] Refactor the openglwidget class
- [x] Update the openglwidget class to work with the new renderer
## Qt + OpenGL rendering
- [x] Add perspective projection from OpenGL lib
- [x] Fix the scaling factor of the perspective projection
- [x] Fix incorrect spawning of the models
- [x] Fix the models moving out of view with each repaint
- [x] Add function for polygons render 
- [x] Add orthogonal projection from OpenGL lib
- [x] Debug rotation
## Screenshots and gifs
- [x] Add functionality for the screen button (the program must provide the ability to save in .bmp and .jpg)
- [x] Add functionality for the gif button (record a gif-animation (640x480, 10fps, 5s))
## Tests
- [x] Add tests
## Final
- [x] Update Makefile for release version
- [x] Add content to the manual.texi document

**Comment by vvoidcat** [comment]
all done
